version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: sa
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-net

  spring-boot-app:
    image: dockerrohit12/accounts:s4
    container_name: spring-container
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - springboot-mysql-net

networks:
  my-network:
